### ISSUE TITLE
Suggestion: Make the quiz more playable with keyboard

### ISSUE THREAD

**Issue by edward6d** [zenorogue/isitrl#2]
I really appreciated how the quiz self-references itself, letting us choose our verdict on its roguelikeness in the help section. We could go a step further and add keybindings to the quiz answers, letting us [c]hoose [t]he a[n]swers in a t[r]ue tra[d]itional r[o]guelike [f]ashion !

(last but not least, it would also make speedrunning the quiz easier 😆)

**Comment by zenorogue** [comment]
Thanks for the suggestion! Added some keybindings.
